// Every command the frontend may invoke has to be listed here: tauri-plugin
// generates one `allow-<command>` / `deny-<command>` permission per entry into
// permissions/autogenerated/, and a command with no permission is rejected by
// the ACL before it reaches Rust. Those files are written into the source tree,
// not OUT_DIR, so a change here has to be committed along with them —
// permissions/default.toml is hand-written and has to be edited by hand.
//
// register_listener and remove_listener are not ours: they are what
// `addPluginListener('voice', …)` and `PluginListener.unregister()` in
// @tauri-apps/api call. Tauri core implements neither, so they still have to be
// declared commands here, or the dictation event can never be subscribed to.
const COMMANDS: &[&str] = &[
    "start_dictation",
    "stop_dictation",
    "cancel_dictation",
    "set_indicator_probe",
    "release_microphone",
    "stop_speaking",
    "speech_probe",
    "speech_live",
    "speech_report",
    "register_listener",
    "remove_listener",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).ios_path("ios").build();
}
