// Every command the frontend may invoke has to be listed here: tauri-plugin
// generates one `allow-<command>` / `deny-<command>` permission per entry into
// permissions/autogenerated/, and a command with no permission is rejected by
// the ACL before it reaches Rust. Those files are written into the source tree,
// not OUT_DIR, so a change here has to be committed along with them —
// permissions/default.toml is hand-written and has to be edited by hand.
const COMMANDS: &[&str] = &["is_available", "open_in"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).ios_path("ios").build();
}
