// Every command the frontend may invoke has to be listed here: tauri-plugin
// generates one `allow-<command>` / `deny-<command>` permission per entry into
// permissions/autogenerated/, which is committed along with this file.
// permissions/default.toml is hand-written.
const COMMANDS: &[&str] = &["read_body"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).ios_path("ios").build();
}
