// Public surface of the per-topic AI observations module (docs/02 part 2, M8).

export type {
  EvidenceAnchors,
  Observation,
  ObservationHit,
  ObservationIndexEntry,
  ObservationPatch,
  ObservationType,
  RetainInput,
} from "./record/types";
export { OBSERVATION_TYPES, isObservationType } from "./record/types";
export {
  isoDate,
  localDate,
  parseIndex,
  parseObservation,
  serializeIndexLine,
  serializeObservation,
} from "./record/files";
export {
  ObservationFileStore,
  type ObservationConflict,
  type ObservationFs,
  type ObservationMeta,
} from "./record/store";
export { FileObservationAdapter, type ObservationAdapter } from "./record/adapter";
export { buildObservationSnapshot, observationPromptSection, trimObservations } from "./record/snapshot";
export {
  assembleIdentity,
  assembleReadingContext,
  assembleReadingSignal,
  READING_SIGNAL_BUDGET,
  type TopicObservationSignal,
} from "./assemble";
export { buildObservationTools, type ObservationToolOptions, type ObservationWriteAction } from "./record/tools";
export {
  buildDistillAgent,
  buildDistillSystemPrompt,
  buildDistillUserMessage,
  buildMarksDistillAgent,
  buildMarksDistillSystemPrompt,
  buildMarksDistillUserMessage,
  classifyDistillFailure,
  countNewReaderMessages,
  countNewUnitMessages,
  datingRule,
  distillCoverage,
  distillFailurePayload,
  evidenceDates,
  formatEvidenceSpan,
  formatSilentMarks,
  markCursor,
  messageCursor,
  runDistillPass,
  runDistillation,
  runMarksDistillPass,
  runMarksDistillation,
  selectSilentMarks,
  DISTILL_AGENT_NAME,
  DISTILL_BRIEF_TOKENS,
  DISTILL_MAX_ROUNDS,
  MARKS_DISTILL_AGENT_NAME,
  type DistillAnnotation,
  type DistillCoverage,
  type DistillDeps,
  type DistillFailureInput,
  type DistillFailureReason,
  type DistillFailureStage,
  type DistillInput,
  type DistillMessage,
  type DistillPassDeps,
  type DistillPassInput,
  type DistillPassResult,
  type DistillPassStore,
  type DistillResult,
  type DistillSkip,
  type DistillUnitPart,
  type EvidenceDates,
  type MarksDistillInput,
  type MarksPassInput,
  type MarksPassResult,
} from "./distill/distill";
export {
  countNewMarks,
  distillUnitOf,
  distillUnits,
  isTopicDue,
  maxBookMarks,
  pagelessMarkIds,
  selectDistillJob,
  threadArrears,
  toDistillAnnotations,
  topicDebt,
  MIN_DISTILL_GAP_MS,
  MIN_NEW_MARKS,
  MIN_NEW_MESSAGES,
  SWEEP_INTERVAL_MS,
  type BookArrears,
  type DistillJob,
  type DistillUnit,
  type ThreadArrears,
  type TopicArrears,
  type UnitThread,
} from "./distill/arrears";
export {
  buildGuessAgent,
  buildGuessSystemPrompt,
  buildGuessTool,
  buildGuessUserMessage,
  composeProfile,
  declaredText,
  formatAttentionTail,
  formatTopicEvidence,
  guessPromptBlock,
  isGuessDue,
  normalizeGuesses,
  profileForPrompt,
  renderGuessLine,
  renderGuessSection,
  replaceDeclared,
  runProfileGuessPass,
  splitProfile,
  GUESS_AGENT_NAME,
  GUESS_BEGIN,
  GUESS_END,
  GUESS_MIN_GAP_MS,
  GUESS_SECTION_CHARS,
  GUESS_TOOL_NAME,
  MAX_GUESSES,
  PROFILE_CHARS,
  type GuessState,
  type GuessTopicEvidence,
  type ProfileGuess,
  type ProfileGuessDeps,
  type ProfileGuessInput,
  type ProfileGuessPassInput,
  type ProfileGuessResult,
  type ProfileGuessStore,
  type ProfileSplit,
  type RawGuess,
} from "./profile/guess";
export {
  buildRehearsalDistillAgent,
  buildRehearsalDistillSystemPrompt,
  buildRehearsalDistillUserMessage,
  runRehearsalDistillation,
  runRehearsalDistillPass,
  selectNewMessages,
  REHEARSAL_DISTILL_AGENT_NAME,
  type RehearsalDistillInput,
  type RehearsalPassDeps,
  type RehearsalPassInput,
  type RehearsalPassResult,
  type RehearsalPassStore,
} from "./distill/rehearsal";
export {
  distillMarks,
  distillRehearsal,
  distillThread,
  getLastDistillation,
  getObservationAdapter,
  listObservationConflicts,
  notifyObservationChange,
  onObservationChange,
  startDistillSweeps,
  sweepDistillation,
  sweepProfileGuess,
  type DistillMarksOptions,
  type DistillRehearsalOptions,
  type DistillThreadOptions,
  type DistillTrigger,
} from "./live";
