// Public surface of the per-topic AI observations module (docs/02 part 2, M8).

export type {
  EvidenceAnchors,
  Observation,
  ObservationHit,
  ObservationIndexEntry,
  ObservationPatch,
  ObservationType,
  RetainInput,
} from "./observations/types";
export { OBSERVATION_TYPES, isObservationType } from "./observations/types";
export {
  isoDate,
  localDate,
  parseIndex,
  parseObservation,
  serializeIndexLine,
  serializeObservation,
} from "./observations/files";
export {
  ObservationFileStore,
  type ObservationConflict,
  type ObservationFs,
  type ObservationMeta,
} from "./observations/store";
export { FileObservationAdapter, type ObservationAdapter } from "./observations/adapter";
export { buildObservationSnapshot, observationPromptSection, trimObservations } from "./observations/select";
export {
  anchorSiblings,
  buildAnchorIndex,
  mentionedIds,
  observationsById,
  observationsForAnnotation,
  observationsForMessage,
  resolveReferences,
  type AnchorIndex,
  type ResolvedReferences,
} from "./observations/links";
export {
  assembleIdentity,
  assembleReadingContext,
  assembleReadingSignal,
  READING_SIGNAL_BUDGET,
  type TopicObservationSignal,
} from "./live/assemble";
export { buildObservationTools, type ObservationToolOptions, type ObservationWriteAction } from "./observations/tools";
export {
  buildDistillAgent,
  buildDistillSystemPrompt,
  buildDistillUserMessage,
  buildMarksDistillAgent,
  buildMarksDistillSystemPrompt,
  buildMarksDistillUserMessage,
  classifyDistillFailure,
  countNewReaderMessages,
  countNewUnitMessages,
  datingRule,
  distillCoverage,
  distillFailurePayload,
  evidenceDates,
  formatEvidenceSpan,
  formatSilentMarks,
  markCursor,
  markDates,
  messageCursor,
  runDistillPass,
  runDistillation,
  runMarksDistillPass,
  runMarksDistillation,
  selectSilentMarks,
  DISTILL_AGENT_NAME,
  DISTILL_BRIEF_TOKENS,
  DISTILL_MAX_ROUNDS,
  MARKS_DISTILL_AGENT_NAME,
  type DistillAnnotation,
  type DistillCoverage,
  type DistillDeps,
  type DistillFailureInput,
  type DistillFailureReason,
  type DistillFailureStage,
  type DistillInput,
  type DistillMessage,
  type DistillPassDeps,
  type DistillPassInput,
  type DistillPassResult,
  type DistillPassStore,
  type DistillResult,
  type DistillSkip,
  type DistillUnitPart,
  type EvidenceDates,
  type MarksDistillInput,
  type MarksPassInput,
  type MarksPassResult,
} from "./observations/distill";
export {
  countNewMarks,
  distillUnitOf,
  distillUnits,
  isTopicDue,
  maxBookMarks,
  pagelessMarkIds,
  selectDistillJob,
  threadArrears,
  toDistillAnnotations,
  topicDebt,
  MIN_DISTILL_GAP_MS,
  MIN_NEW_MARKS,
  MIN_NEW_MESSAGES,
  SWEEP_INTERVAL_MS,
  type BookArrears,
  type DistillJob,
  type DistillUnit,
  type ThreadArrears,
  type TopicArrears,
  type UnitThread,
} from "./observations/arrears";
export {
  buildGuessAgent,
  buildGuessSystemPrompt,
  buildGuessTool,
  buildGuessUserMessage,
  composeProfile,
  declaredText,
  formatAttentionTail,
  formatTopicEvidence,
  guessPromptBlock,
  isGuessDue,
  normalizeGuesses,
  profileForPrompt,
  renderGuessLine,
  renderGuessSection,
  replaceDeclared,
  runProfileGuessPass,
  splitProfile,
  GUESS_AGENT_NAME,
  GUESS_BEGIN,
  GUESS_END,
  GUESS_MIN_GAP_MS,
  GUESS_SECTION_CHARS,
  GUESS_TOOL_NAME,
  MAX_GUESSES,
  PROFILE_CHARS,
  type GuessState,
  type GuessTopicEvidence,
  type ProfileGuess,
  type ProfileGuessDeps,
  type ProfileGuessInput,
  type ProfileGuessPassInput,
  type ProfileGuessResult,
  type ProfileGuessStore,
  type ProfileSplit,
  type RawGuess,
} from "./profile/guess";
export {
  buildRetellDistillAgent,
  buildRetellDistillSystemPrompt,
  buildRetellDistillUserMessage,
  runRetellDistillation,
  runRetellDistillPass,
  selectNewMessages,
  RETELL_DISTILL_AGENT_NAME,
  type RetellDistillInput,
  type RetellPassDeps,
  type RetellPassInput,
  type RetellPassResult,
  type RetellPassStore,
} from "./observations/retell";
export {
  distillMarks,
  distillRetell,
  distillThread,
  getLastDistillation,
  getObservationAdapter,
  listObservationConflicts,
  notifyObservationChange,
  onObservationChange,
  startDistillSweeps,
  sweepDistillation,
  sweepProfileGuess,
  type DistillMarksOptions,
  type DistillRetellOptions,
  type DistillThreadOptions,
  type DistillTrigger,
} from "./live/live";
