// Highlight-driven auto note generation (docs/14), pure part. Page navigation is
// not a signal (the reader peeks ahead); the reader's highlights are. The
// "highlight frontier" is the furthest chapter (by the plan's page ranges) that
// contains at least one annotation. When the frontier advances past a chapter,
// that chapter is settled: generate it if it has marks, skip it if it has none
// (the reader found nothing worth marking there). The frontier chapter itself is
// never generated by this rule — the reader is still in it.

import type { ChapterStatus } from "./types";

// A chapter as the frontier logic sees it: its page range and current status.
export interface AutoChapter {
  index: number;
  startPage: number;
  endPage: number;
  status: ChapterStatus;
}

// One annotation, reduced to the page it sits on (1-based). Annotations without a
// page are dropped by the caller before they get here.
export interface AutoAnnotation {
  page: number;
}

export interface AutoNotesPlan {
  // Chapter indexes to generate now (behind the frontier, have marks, no note yet).
  generate: number[];
  // Chapter indexes to mark "skipped" (behind the frontier, zero marks, no note yet).
  skip: number[];
}

// The inclusive final-chapter pass (book close / re-attach): the last chapter can
// never be triggered by a "next chapter" highlight, so on close we include it if
// the reading position AND at least one highlight are both in or past it.
export interface FinalPass {
  readingPage: number; // 1-based
}

function chapterHasMark(ch: AutoChapter, annotations: AutoAnnotation[]): boolean {
  return annotations.some((a) => a.page >= ch.startPage && a.page <= ch.endPage);
}

// The furthest chapter index that contains a mark (0 when nothing is marked).
export function highlightFrontier(chapters: AutoChapter[], annotations: AutoAnnotation[]): number {
  let frontier = 0;
  for (const ch of chapters) {
    if (chapterHasMark(ch, annotations)) frontier = Math.max(frontier, ch.index);
  }
  return frontier;
}

// Map the reader's marks onto the chapter plan and decide what to generate and
// what to skip. Only chapters that are still "pending" are touched; done/failed/
// running/skipped chapters are left as they are. Chapters at or past the frontier
// are left pending (the reader may still be reading them). The final pass raises
// the frontier past the last chapter when the reader has clearly finished, so the
// book's tail settles on close.
export function planAutoNotes(
  chapters: AutoChapter[],
  annotations: AutoAnnotation[],
  finalPass?: FinalPass,
): AutoNotesPlan {
  let frontier = highlightFrontier(chapters, annotations);
  if (finalPass && chapters.length > 0) {
    const last = chapters[chapters.length - 1];
    const inOrPastLast = (p: number) => p >= last.startPage;
    if (inOrPastLast(finalPass.readingPage) && annotations.some((a) => inOrPastLast(a.page))) {
      frontier = Math.max(frontier, last.index + 1);
    }
  }

  const generate: number[] = [];
  const skip: number[] = [];
  for (const ch of chapters) {
    if (ch.index >= frontier) continue; // frontier chapter and beyond: still open
    if (ch.status !== "pending") continue; // already settled
    if (chapterHasMark(ch, annotations)) generate.push(ch.index);
    else skip.push(ch.index);
  }
  return { generate, skip };
}
